version: "3.4"
services:
  finder_python:
    restart: always
    build:
      context: ./
      dockerfile: "python-dockerfile"
    environment:
      - "PYTHONUNBUFFERED=1"
    volumes:
      - .:/app
    networks:
      - finder
  finder_nginx:
    restart: always
    build: ./nginx
    ports:
      - "${DOCKER_WEB_PORT}:80"
      - "${DOCKER_WEB_SSL_PORT}:443"
    volumes:
      - .:/app
    depends_on:
      - finder_python
    networks:
      - finder
networks:
  finder:
    driver: "bridge"
